/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as rootIndexImport } from './routes/(root)/index'

// Create/Update Routes

const rootIndexRoute = rootIndexImport.update({
  id: '/(root)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(root)/': {
      id: '/(root)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof rootIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof rootIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(root)/': typeof rootIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(root)/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  rootIndexRoute: typeof rootIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  rootIndexRoute: rootIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(root)/"
      ]
    },
    "/(root)/": {
      "filePath": "(root)/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
